name: Paddle docker images

outputs:
  docker-image:
    description: The docker image to use for the rest of the workflow
    value: ${{ steps.check-image.outputs.docker-image }}

runs:
  steps:
    - name: check docker image
      id: check-image
      shell: bash
      run: echo "docker-image=123123" >> "${GITHUB_OUTPUT}"
